# Generated by Django 3.2.6 on 2021-08-16 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته بندی')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')),
                ('positions', models.IntegerField(default=True, verbose_name='پوزیشن')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='تیتر')),
                ('body', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(upload_to='image/', verbose_name='انتخاب عکس')),
                ('time', models.DateTimeField(verbose_name='زمان')),
                ('status', models.CharField(choices=[('draft', 'غیر فعال'), ('published', 'فعال')], default='published', max_length=10, verbose_name='وضعیت')),
                ('daste', models.ManyToManyField(related_name='articles', to='charity.Tag', verbose_name='دسته بندی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقالات',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
