# Generated by Django 3.2.6 on 2021-08-30 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل'},
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image/profile/', verbose_name='انتخاب عکس'),
            preserve_default=False,
        ),
    ]
