# Generated by Django 3.2.6 on 2021-08-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_profile_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
