# Generated by Django 3.2.6 on 2021-08-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210831_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='image/profile/aaaa.png', upload_to='image/profile/', verbose_name='انتخاب عکس'),
        ),
    ]
